--- @meta
-- Type definitions for the TSFX global consumer API
-- This file is NOT loaded at runtime - only for LuaLS type checking

---@class TSFXGlobal
---@field Log LogInstance
---@field Events EventBusClass
---@field Cache CacheClass
---@field Locale LocaleClass
---@field StateMachine StateMachineClass
---@field StateMachineBuilder StateMachineBuilderClass
---@field Player fun(source: number): PlayerHandleClass
---@field Job fun(name: string): JobHandleClass
---@field Gang fun(name: string): GangHandleClass
---@field Framework fun(): FrameworkHandleClass
---@field Inventory InventoryHandleClass
---@field Notify NotifyHandleClass
---@field Target TargetHandleClass
---@field Players PlayersModule
