--- @meta
-- Type definitions for TSFX Interact Adapters
-- This file is NOT loaded at runtime - only for LuaLS type checking

---@class InteractCallbackData
---@field entity? number Entity handle. nil when no entity is involved (coord/zone targets).
---@field coords vector3 World position where the interaction was triggered.
---@field distance number Player distance from coords at time of selection.
---@field zone? number Zone id. Populated by ox_target for zone-based targets only.
---@field name? string Option name. Populated by sleepless_interact for active callbacks only.

---@class InteractOption
---@field label string
---@field name? string Identifier used when removing a specific option.
---@field icon? string Font Awesome icon name.
---@field iconColour? string
---@field distance? number Max distance at which the option is displayed.
---@field canInteract? fun(entity: number, distance: number, coords: vector3, name: string, bone: string): boolean
---@field onSelect? fun(data: InteractCallbackData)
---@field groups? string|string[]|table<string, number>
---@field items? string|string[]|table<string, number>
---@field anyItem? boolean
---@field bones? string|string[]
---@field event? string
---@field serverEvent? string
---@field command? string
---@field export? string
---@field onActive? fun(data: InteractCallbackData)
---@field onInactive? fun(data: InteractCallbackData)
---@field whileActive? fun(data: InteractCallbackData)
---@field holdDuration? number
---@field cooldown? number

---@class SphereZoneParams
---@field coords vector3
---@field name? string
---@field radius? number
---@field debug? boolean
---@field drawSprite? boolean
---@field options InteractOption|InteractOption[]

---@class BoxZoneParams
---@field coords vector3
---@field name? string
---@field size? vector3
---@field rotation? number
---@field debug? boolean
---@field drawSprite? boolean
---@field options InteractOption|InteractOption[]

---@class PolyZoneParams
---@field points vector3[]
---@field name? string
---@field thickness? number
---@field debug? boolean
---@field drawSprite? boolean
---@field options InteractOption|InteractOption[]
